### ISSUE TITLE
Hi, how can get if user rating the app or not

### ISSUE THREAD

**Issue by rami-al-rahim** [google-unity/in-app-review#1]
Please help me

**Comment by aprius** [comment]
Hi, sorry abour repy late

Currently, google's In-App-Review does not support API to detect whether you really rate the app or not

**Comment by aprius** [comment]
Instead you can implement your own thread to increase the likelihood that users will rate your app

**Comment by YuliyF** [comment]
Plugin stop working in Unity 2022 (run in 2022.3.5 - 2022.3.7)! On 2021 - are working. Using version": 1.8.1

**Comment by aprius** [comment]
> Plugin stop working in Unity 2022 (run in 2022.3.5 - 2022.3.7)! On 2021 - are working. Using version": 1.8.1

Okay, I will test it with 2022 tomorrow and let you know the result

**Comment by aprius** [comment]
> Plugin stop working in Unity 2022 (run in 2022.3.5 - 2022.3.7)! On 2021 - are working. Using version": 1.8.1

Hi, i just did a quick test with Unity 2022.3.7f1 and in-app-review 1.8.1 and it works fine

**Comment by aprius** [comment]
![image](https://github.com/google-unity/in-app-review/assets/44673303/a01ff594-60ab-4f66-a739-da972ff4def5)

If you see your logcat like this, please make sure you are using a personal gmail account and not a business or corporate account

![Screenshot_20230818-113717_Google Play Store](https://github.com/google-unity/in-app-review/assets/44673303/ed255e7b-d2d7-4f35-9acd-e6d1b54423fa)

**Comment by aprius** [comment]
Please make sure that you have followed google test instructions properly

https://developer.android.com/guide/playcore/in-app-review/test#troubleshooting

If it still doesn't work please tell me your setup,

**Comment by YuliyF** [comment]
@yenmoc, thanks for tests. I see in logcat this:
```
Info PlayCore UID: [10924]  PID: [27694] ReviewService : Unbind from service.
Info Unity RequestReview: requestFlowOperation=NoError, IsSuccessful=True       - it's my string from code
Info Unity LaunchReviewFlow: launchFlowOperation=NoError, IsSuccessful=True   - it's my string from code
Warn JavaBinder BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.play.core.review.internal.zzl
```
What is it mean: Unbind from service - ?

**Comment by aprius** [comment]
@YuliyF  As you can see in the logcat launchFlowOperation=NoError means there is no error about calling LaunchReviewFlow.
Do you use your personal gmail account to request a review?

**Comment by YuliyF** [comment]
> @YuliyF As you can see in the logcat launchFlowOperation=NoError means there is no error about calling LaunchReviewFlow. Do you use your personal gmail account to request a review?

Yes, you are right, problem in my email. Thanks
