### ISSUE TITLE
Cant update to 1.8.2 due to dependencies

### ISSUE THREAD

**Issue by EthanSK** [google-unity/in-app-review#10]
The dependencies of 1.8.2 are not on openUPM so it can't update...

[Package Manager Window] Error adding package: com.google.play.review@1.8.2.
Unable to add package [com.google.play.review@1.8.2]:
  Package com.google.play.review@1.8.2 has invalid dependencies or related test packages:
    com.google.play.common (dependency): Package [com.google.play.common@1.9.1] cannot be found
    com.google.play.core (dependency): Package [com.google.play.core@1.8.4] cannot be found
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:384)

**Comment by aprius** [comment]
so maybe OpenUPM haven't updated yet. Can you update manually with manifest?

**Comment by aprius** [comment]
I just tried installing using manifest and they still work fine. So I think the problem is probably on the OpenUPM side. Can you try again on an empty project?

**Comment by EthanSK** [comment]
I mean when I add the play core and common dependencies required by the new version to the manifest I still get an error:

```An error occurred while resolving packages:

  Project has invalid dependencies:
    com.google.play.common: Package [com.google.play.common@1.9.1] cannot be found
    com.google.play.core: Package [com.google.play.core@1.8.4] cannot be found

```

**Comment by EthanSK** [comment]
I got it to work for now with
```

 "com.google.play.review": "https://github.com/google-unity/in-app-review.git#1.8.2",
    "com.google.play.core": "https://github.com/google-unity/google-play-core.git#1.8.4",
    "com.google.play.common": "https://github.com/google-unity/google-play-common.git#1.9.1",
    "com.google.android.appbundle": "https://github.com/google-unity/android-app-bundle.git#1.9.0",
    "com.google.external-dependency-manager": "https://github.com/google-unity/external-dependency-manager.git#1.2.172",
```
