### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by devon-o** [google-unity/in-app-review#2]
When attempting to launch a review flow, the following java error is thrown:
```
AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='addOnSuccessListener' signature='(Lcom.google.android.gms.tasks.OnSuccessListener;)Ljava/lang/Object;' in class Ljava.lang.Object;
```
This actually seems reasonable because when I follow the code path I see this:

in `Google.Play.Review.Internal.ReviewPlayServicesTaskManager::RequestReviewFlow ` the line `var javaTask = _javaReviewManager.Call<AndroidJavaObject>("requestReviewFlow");` is called.
This javaTask var is actually a java `com.google.android.play.core.tasks.Task` object.

In `Google.Play.Core.Internal.PlayServicesTask::RegisterOnSuccessCallback` the method `addOnSuccessListener()` is called on that java object but it is passed a `com.google.android.gms.tasks.OnSuccessListner` java object when it actually expects a `com.google.android.play.core.tasks.OnSuccessListener`.

So, the original error is really due to a signature mismatch. addOnSuccessListener() expects a play.core.tasks.OnSuccessListener, but receives a gms.tasks.OnSuccessListener instead.

Am I missing something here?

I am using:
- Unity 2021.3.22f1 
- com.google.play.core-1.8.2.tgz 
- com.google.play.review-1.8.1.tgz 
- com.google.play.common-1.8.2.tgz 

I have also tried play core 1.8.1 and play common 1.8.1 with the same result.

I thank anyone for any help/tips/suggestions

**Comment by aprius** [comment]
Are you sure that the library files are included when building? If not, edit the progruad file as in the readme. If so, try downgrading the version of the generated arr files or you can submit the native plugin versions created when resolving here.

**Comment by devon-o** [comment]
Aha! Our gradle build file is so highly customized that it's difficult to keep track of all included libs. I double checked the android resolver though and compared it to what was being included in the build and discovered we were missing 2 libs. For the sake of posterity, I've now added: core-common-2.0.0, and review-2.0.0 lib files.

This seems to resolve the issue.

Thank you for pointing me in the right direction, [yenmoc](https://github.com/yenmoc)

-Devon
