### ISSUE TITLE
Review window isnt shown with unity version 2022.3.14, plugin 1.8.1

### ISSUE THREAD

**Issue by marcozakaria** [google-unity/in-app-review#4]
Hey @yenmoc  i am using Unity 2022.3.14f with plugin version 1.8.1, used same sample code that in readme and added custom proguarde file with code in readme but when i request review nothing happens and no error is thrown in logs , 
build i am testing is downloaded from playstore , could you please help

**Comment by marcozakaria** [comment]
![rating logs](https://github.com/google-unity/in-app-review/assets/24639480/ad628932-3001-491a-ba37-dd8f7fa9b81f)
[RatingScript.txt](https://github.com/google-unity/in-app-review/files/14151376/RatingScript.txt)
this is the script i used and logs when i ` RateAndReview()` function

**Comment by aprius** [comment]
Did you test with the app uploaded to internal testing on google play console?

**Comment by marcozakaria** [comment]
> Did you test with the app uploaded to internal testing on google play console?

I tested the beta version and production none of them show the window or throw error 
Tried it on 3 different devices

**Comment by aprius** [comment]
In case you have tested with the production version downloaded from the play store but the app review does not appear, there may be a problem with your account logging into the Google Play store. Can you try changing to another personal account of yours?

**Comment by marcozakaria** [comment]
> In case you have tested with the production version downloaded from the play store but the app review does not appear, there may be a problem with your account logging into the Google Play store. Can you try changing to another personal account of yours?

Tried with a different phone that has another account logged in and nothing shown when I  pressed rate

**Comment by aprius** [comment]
In such case can you setup a sample repo the way you setup then I will help you test it.
