### ISSUE TITLE
Duplicate class error 

### ISSUE THREAD

**Issue by HassannKhan** [google-unity/in-app-review#6]
* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class android.support.v4.os.ResultReceiver found in modules core-1.9.0-runtime (androidx.core:core:1.9.0) and jetified-com.android.support.support-compat-26.1.0-runtime (:com.android.support.support-compat-26.1.0:)
     Duplicate class android.support.v4.os.ResultReceiver$1 found in modules core-1.9.0-runtime (androidx.core:core:1.9.0) and jetified-com.android.support.support-compat-26.1.0-runtime (:com.android.support.support-compat-26.1.0:)
     Duplicate class android.support.v4.os.ResultReceiver$MyResultReceiver found in modules core-1.9.0-runtime (androidx.core:core:1.9.0) and jetified-com.android.support.support-compat-26.1.0-runtime (:com.android.support.support-compat-26.1.0:)
     Duplicate class android.support.v4.os.ResultReceiver$MyRunnable found in modules core-1.9.0-runtime (androidx.core:core:1.9.0) and jetified-com.android.support.support-compat-26.1.0-runtime (:com.android.support.support-compat-26.1.0:)
     Duplicate class androidx.annotation.AnimRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.AnimatorRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.AnyRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.AnyThread found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.ArrayRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.AttrRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.BinderThread found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.BoolRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.CallSuper found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.CheckResult found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.ColorInt found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.ColorLong found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.ColorRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.DimenRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.Dimension found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.DrawableRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.FloatRange found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.FontRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.FractionRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.GuardedBy found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.HalfFloat found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.IdRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.IntDef found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.IntRange found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.IntegerRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.InterpolatorRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.Keep found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.LayoutRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.MainThread found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.MenuRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.NonNull found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.Nullable found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.PluralsRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.Px found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.RawRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.RequiresApi found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.RequiresPermission found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.RequiresPermission$Read found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.RequiresPermission$Write found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.RestrictTo found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.RestrictTo$Scope found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.Size found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.StringDef found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.StringRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.StyleRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.StyleableRes found in modules annotation-1.3.0 (androidx.annotation:annotation:1.3.0) and jetified-com.android.support.support-annotations-26.1.0 (com.android.support.support-annotations-26.1.0.jar)
     Duplicate class androidx.annotation.TransitionRes <message truncated>

**Comment by aprius** [comment]
@Hassan1Khan Most duplicate cases are caused by version conflicts between plugins. This is mainly due to project configuration so if it is still a problem for you, can you create a repository with the following plugins? setup google plugins in your project so I can easily find the cause?

**Comment by HassannKhan** [comment]
@yenmoc  It's an empty project with only In-App Review plugin in it. Duplication errors arose after simple resolve of dependencies.

**Comment by aprius** [comment]
Do you use mainTemplate.gradle to resolve dependencies?

**Comment by aprius** [comment]
Currently I still use InAppReview in parallel with Admob, Applovin, PlayGameService on unity 2022 without any problems.

**Comment by HassannKhan** [comment]
@yenmoc I tried both With and without mainTemplate.gradle
Without it, I see duplication error
With it, the popup never opens 




I am using unity version 2023.2.2f1

**Comment by aprius** [comment]
@Hassan1Khan Please try upgrading EDM4U to the latest version v1.2.179. Try to see if the resolve success popup appears or not?

**Comment by HassannKhan** [comment]
@yenmoc  THANK YOU SO MUCH !!! Your Suggestion worked. I got rid of frustrating duplicate error by using EDM4U's latest version v1.2.179 and the rate popup also worked after that. THANK YOU once again.
