### ISSUE TITLE
Mistake in the "Known Issues" section

### ISSUE THREAD

**Issue by pboitier** [google-unity/in-app-review#7]
The fix for the known issues is not valid Proguard syntax. The correct lines are:

`-keep class com.google.android.play.core.** { *; }`
`-keep class com.google.android.gms.play-** { *; }`

Please fix it so others don't get stuck with this! Thanks!

**Comment by aprius** [comment]
Oh, There was a typo here, thank you for pointing it out

**Comment by pboitier** [comment]
Thank you for fixing it!
