### ISSUE TITLE
Is latest version of com.google.android.play.review 2.0.0?

### ISSUE THREAD

**Issue by Won-gyu** [google-unity/in-app-review#8]
I wonder if the latest version of this review plugin is 2.0.0.
Also, I have ExternalDependencyManager v1.2.177 from Firebase SDK while your instruction requires v1.2.172.
Is it okay to use a higher version of ExternalDependencyManager?

**Comment by aprius** [comment]
Yes, You can use the latest version of EDM4U without any problem with in-app-review
