### ISSUE TITLE
Outdated dependency com.google.android.play:core

### ISSUE THREAD

**Issue by SAsheulov** [google-unity/in-app-review#9]
The following email arrived from Google:
![image](https://github.com/google-unity/in-app-review/assets/43669322/f8fbb4bd-e414-4a9d-ba27-372d0b9821e7)
Link from mail: https://developer.android.com/guide/playcore#playcore-migration

Are you planning to update this plugin with updated dependencies? And when it will be?

**Comment by aprius** [comment]
I will check and update now

**Comment by aprius** [comment]
Can you try updating to the new version `1.8.2` to see if the problem still occurs?

**Comment by EthanSK** [comment]
Can't update https://github.com/google-unity/in-app-review/issues/10

**Comment by SAsheulov** [comment]
I have updated the plugin to the latest version, tested its functionality, and confirmed that it works correctly. Additionally, I have checked the dependency tree in the Android Project and can confirm that versions of the used Android libraries are current.

While I have not yet uploaded the application to Google Play, it seems the issue is resolved.

**Comment by SAsheulov** [comment]
I have updated the plugin to the latest version, tested its functionality, and confirmed that it works correctly. Additionally, I have checked the dependency tree in the Android Project and can confirm that versions of the used Android libraries are current.

While I have not yet uploaded the application to Google Play, it seems the issue is resolved.
